### ISSUE TITLE
Segmentation fault when stress testing

### ISSUE THREAD

**Issue by bitkevin** [btccom/explorer-kv#1]
with `libjemalloc`:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tparser -c tparser.conf -l tparser.log'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbafa51e12d in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
(gdb) bt
#0  0x00007fbafa51e12d in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007fbafa5370ef in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#2  0x00007fbafa51759f in calloc () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#3  0x00007fbaf88da9b3 in evbuffer_new () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#4  0x00007fbaf86ba618 in _evhtp_connection_new () from /usr/local/lib/libevhtp.so.1.2.10
#5  0x00007fbaf86ba8d4 in _evhtp_accept_cb () from /usr/local/lib/libevhtp.so.1.2.10
#6  0x00007fbaf88e23fa in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#7  0x00007fbaf88d5f24 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#8  0x00000000006a5d9d in APIServer::run (this=0x2a94518) at /work/zhibiao.pan/Explorer-v3/jiexi/src/HttpAPI.cc:942
#9  0x0000000000606133 in Parser::run (this=0x2a8c000) at /work/zhibiao.pan/Explorer-v3/jiexi/src/Parser.cc:484
#10 0x00000000005f8559 in main (argc=5, argv=0x7fff69507a78) at /work/zhibiao.pan/Explorer-v3/jiexi/src/tparser/TParserMain.cc:135
```

with `libtcmalloc`:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tparser -c tparser.conf -l tparser.log'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2e63776e4f in tc_malloc () from /usr/lib/libtcmalloc.so.4
(gdb) bt
#0  0x00007f2e63776e4f in tc_malloc () from /usr/lib/libtcmalloc.so.4
#1  0x00007f2e62844dcb in htparser_new () from /usr/local/lib/libevhtp.so.1.2.10
#2  0x00007f2e628406fc in _evhtp_connection_new () from /usr/local/lib/libevhtp.so.1.2.10
#3  0x00007f2e628408d4 in _evhtp_accept_cb () from /usr/local/lib/libevhtp.so.1.2.10
#4  0x00007f2e62a683fa in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#5  0x00007f2e62a5bf24 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#6  0x00000000006a5d9d in APIServer::run (this=0x2d96518) at /work/zhibiao.pan/Explorer-v3/jiexi/src/HttpAPI.cc:942
#7  0x0000000000606133 in Parser::run (this=0x2d8e000) at /work/zhibiao.pan/Explorer-v3/jiexi/src/Parser.cc:484
#8  0x00000000005f8559 in main (argc=5, argv=0x7fffa7d579c8) at /work/zhibiao.pan/Explorer-v3/jiexi/src/tparser/TParserMain.cc:135
```

**Comment by bitkevin** [comment]
fixed by : https://github.com/btccom/explorer-kv/commit/5faa78aea498634a218c248b3b388ae70ef940ff
